config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: test/sqaaas_simplified
      repo: https://gitlab.com/dtgeo/workflow-registry
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-lavender-monkey.sh
        container: qc.acc_flimsy-smalt-russel
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-goldenrod-jackal.sh
        container: qc.doc_grumpy-saffron-macaw
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-yellow-tetra.sh
        container: qc.doc_homey-orchid-gerbil
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-scarlet-raccoon.sh
        container: qc.doc_whiny-cinnabar-slug
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-violet-buffalo.sh
        container: qc.lic_wimpy-wisteria-elephant
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-taupe-anteater.sh
        container: qc.ver_ready-emerald-raccoon
timeout: 5400
