config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: main
      repo: https://gitlab.com/dtgeo/workflow-registry
      subfolder: example_workflow/matmul
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-heliotrope-weasel.sh
        container: qc.acc_sleazy-harlequin-moth
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-mustard-hyena.sh
        container: qc.doc_sloppy-grey-quokka
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lilac-rabbit.sh
        container: qc.doc_lanky-cobalt-llama
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-salmon-zorse.sh
        container: qc.doc_trippy-tan-clam
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-turquoise-tortoise.sh
        container: qc.lic_wheezy-charcoal-weasel
  QC.Sec:
    repos:
      gitlab.com/dtgeo/workflow-registry bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-bistre-kudu.sh
        container: qc.sec_squeaky-gold-orangutan
  QC.Sty:
    repos:
      gitlab.com/dtgeo/workflow-registry flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-persimmon-chow.sh
        container: qc.sty_snazzy-seashell-affenpinscher
  QC.Uni:
    repos:
      gitlab.com/dtgeo/workflow-registry pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olivine-angelfish.sh
        container: qc.uni_wheezy-burgundy-stingray
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cinnamon-giraffe.sh
        container: qc.ver_scanty-orchid-llama
timeout: 5400
