config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: test/sqaaas_simplified
      repo: https://gitlab.com/dtgeo/workflow-registry
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-platinum-stingray.sh
        container: qc.acc_pasty-pear-saola
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-burgundy-frise.sh
        container: qc.doc_bluesy-magenta-kangaroo
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-linen-rattlesnake.sh
        container: qc.doc_cloudy-dandelion-starfish
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cobalt-hare.sh
        container: qc.doc_lovely-saffron-moth
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-bistre-guppy.sh
        container: qc.lic_freaky-azure-insect
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cerise-lemur.sh
        container: qc.ver_flabby-white-dachsbracke
timeout: 5400
