config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: test/sqaaas_simplified
      repo: https://gitlab.com/dtgeo/workflow-registry
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-mauve-scorpion.sh
        container: qc.acc_queasy-vermilion-collie
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cyan-blue.sh
        container: qc.doc_sickly-yellow-leopard
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-sapphire-argentino.sh
        container: qc.doc_freaky-violet-zebu
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-champagne-mouse.sh
        container: qc.doc_ugly-purple-rattlesnake
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lavender-heron.sh
        container: qc.lic_snappy-tomato-spitz
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-burgundy-avocet.sh
        container: qc.ver_leaky-chocolate-dane
timeout: 5400
