config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: test/sqaaas_simplified
      repo: https://gitlab.com/dtgeo/workflow-registry
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-myrtle-hummingbird.sh
        container: qc.acc_crabby-green-quetzal
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-teal-dachsbracke.sh
        container: qc.doc_flaky-cardinal-crocodile
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-bistre-havanese.sh
        container: qc.doc_slaphappy-tan-cattle
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-buff-grasshopper.sh
        container: qc.doc_scummy-heliotrope-lynx
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-alizarin-seahorse.sh
        container: qc.lic_lumpy-beige-sparrow
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-asparagus-penguin.sh
        container: qc.ver_baggy-sapphire-russel
timeout: 5400
