config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: WP5/DTCV2/WF5201
      repo: https://gitlab.com/dtgeo/workflow-registry
      subfolder: DTC52/WF5201/ST520101
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cyan-cuscus.sh
        container: qc.acc_muggy-cinnamon-ibis
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-smalt-insect.sh
        container: qc.doc_homely-orange-bobcat
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-pink-falcon.sh
        container: qc.doc_smelly-magenta-dollar
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ecru-corgi.sh
        container: qc.doc_nippy-sepia-macaque
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-xanthic-walrus.sh
        container: qc.lic_shabby-razzmatazz-dollar
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-pear-gopher.sh
        container: qc.ver_bluesy-teal-birman
timeout: 5400
