config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo/workflow-registry:
      branch: test/sqaaas_simplified
      repo: https://gitlab.com/dtgeo/workflow-registry
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-smalt-liger.sh
        container: qc.acc_craggy-viridian-moth
  QC.Doc:
    repos:
      gitlab.com/dtgeo/workflow-registry find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-white-kangaroo.sh
        container: qc.doc_frumpy-seashell-eleuth
      gitlab.com/dtgeo/workflow-registry git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cream-blue.sh
        container: qc.doc_flaky-cerise-buzzard
      gitlab.com/dtgeo/workflow-registry markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cornflower-tiger.sh
        container: qc.doc_squirrely-ivory-dogfish
  QC.Lic:
    repos:
      gitlab.com/dtgeo/workflow-registry licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-firebrick-panda.sh
        container: qc.lic_muzzy-persimmon-worm
  QC.Ver:
    repos:
      gitlab.com/dtgeo/workflow-registry get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lemon-grasshopper.sh
        container: qc.ver_lovely-indigo-rat
timeout: 5400
